NUMPY

In [85]:
import numpy as np

NumPy Array

In [25]:
nums = list(range(1,11))
arr = np.array(nums)
type(arr)

numpy.ndarray

In [34]:
arr = np.array([1,2,3,4,5])
nums = [1,2,3,4,5]
print(nums)
arr

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [81]:
arr = np.arange(10) # arange() function is used to create an array upto a certain range.
arr

# Creaing a 2D array
nums = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # Three square brackets ([[[]]])
nums.ndim # To find the dimension of the array.


3

In [ ]:
# Creating a 3D array using 2D arrays.
arr = np.array([[[1,2,3],[2,3,4]], [[5,8,2],[9,1,7]]])
arr.ndim
arr

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 8, 2],
        [9, 1, 7]]])

In [ ]:
# Creating a 2D arrays with zeros.
arr = np.zeros([3,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Creating a 2D arrays with ones.
arr = np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
# Creating an array upto a certain range with elements with equal difference bw them.
arr = np.linspace(1,10,5) # Array of 5 numbers from 1 to 10 with equal difference bw them.
print(arr)
nums = np.linspace(1,10,6).reshape(3,2) # Converting it into a 2D array.
print(nums)
nums1 = np.linspace(1,10,8).reshape(2,2,2) # Converting it into a 3D array.
print(nums1)

[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
[[[ 1.          2.28571429]
  [ 3.57142857  4.85714286]]

 [[ 6.14285714  7.42857143]
  [ 8.71428571 10.        ]]]


In [76]:
# Creating a an array upto a range and reshaping it.
arr = np.arange(30).reshape(5,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [ ]:
arr = np.array([[[1,2,3]]]) #This shii is cwazyyy.
arr.ndim
arr.shape

(1, 1, 3)

In [86]:
arr = np.random.randint(1,5,10) # Creating an array of size 10 random numbers  from 1 to 5.
print(arr)
nums = np.random.randint(1,10,(3,4)) # Creating a 2D array.
print(nums) 
nums1 = np.random.randint(1,10,(3,4,3)) # Creating a 3D array.
print(nums1) 

[3 3 2 3 3 3 1 1 4 4]
[[5 3 6 3]
 [3 8 4 2]
 [4 2 6 7]]
[[[6 3 2]
  [8 5 2]
  [7 1 7]
  [9 2 7]]

 [[5 5 1]
  [8 2 3]
  [6 5 6]
  [8 7 4]]

 [[2 9 6]
  [7 2 4]
  [8 4 8]
  [2 4 4]]]
