Array vs List


In [1]:
import numpy as np

In [43]:
GOD_ARRAY = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
nums = [1,2,3,4,5, "Tumse mile to dekho shahar mein khile lagi hai vaadiyan"]
print(type(nums))
numss = np.array(nums)
print(type(numss))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
nums = np.arange(10)
print(nums)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
nums = np.zeros((2,3))
nums

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
nums = np.ones((6,10))
nums

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
nums = np.linspace(1,10,5)
nums

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
nums = np.array([1,2,3,4,5,6])
nums = nums.reshape(2,3)
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
nums = np.random.randint(1,10,10)
nums = nums.reshape(2,5)
print(nums)
print(nums.dtype)
print(nums.size)
print(nums.shape)
print(nums.ndim)

[[2 6 3 2 4]
 [7 2 8 3 6]]
int32
10
(2, 5)
2


In [33]:
nums = np.random.randint(1,10,(3,4))
nums = nums.flatten()
print(nums)


[1 2 5 6 6 6 8 3 1 7 4 3]


In [37]:
nums  = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
nums = np.array(nums)
print(nums.shape)
nums = nums.T
print(nums.shape)

(4, 3)
(3, 4)


In [ ]:
print(GOD_ARRAY[2:8])
print(GOD_ARRAY[2:8:2])

[3 4 5 6 7 8]
[3 5 7]


In [51]:
nums  = [[1,2,3,4,5],[4,5,6,5,6],[7,8,9,7,8],[10,11,12,9,10], [4,5,6,5,6]]
nums = np.array(nums)
nums[0:3, 1:5]

array([[2, 3, 4, 5],
       [5, 6, 5, 6],
       [8, 9, 7, 8]])

In [67]:
nums = np.random.randint(1, 20, (4,5))
print(nums * 2,end="\n-------------------\n")
print(nums + 2)

[[ 4 32 36 16 34]
 [18 30 32 24 22]
 [32 36 12  2 26]
 [34  4 26  2 16]]
-------------------
[[ 4 18 20 10 19]
 [11 17 18 14 13]
 [18 20  8  3 15]
 [19  4 15  3 10]]


In [74]:
nums1 = np.arange(5)
nums2 = np.arange(5)
print(nums1 + nums2)
print(nums1 * nums2)

[0 2 4 6 8]
[ 0  1  4  9 16]


In [ ]:
x = [1,2,3,4,5]
y = [6,7,8,9,10]
print("Addition For List:",x+y)
#print("Mutliplication For List:",x*y) ---> Throws an error.

x = np.array(x)
y = np.array(y)
print("Addition for Array:",x+y)
print("Mulitplication for Array:",x*y)


Addition For List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Addition for Array: [ 7  9 11 13 15]
Mulitplication for Array: [ 6 14 24 36 50]
