### A model to predict the Price of second-hand Bikes.

In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv('Used_Bikes.csv')

In [57]:
# Drop null values.
df.dropna(inplace=True)

In [58]:
# Drop duplicate values.
df.drop_duplicates(inplace = True)

In [59]:
#Dropping unwanted columns.
df.drop(columns=['bike_name', 'city'], inplace=True)

In [60]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [61]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [62]:
dt = {
    "First Owner":1,
    "Second Owner":2,
    "Third Owner":3,
    "Fourth Owner Or More" : 4
}
df['owner'] = df['owner'].map(dt)

In [63]:
df['owner'].unique()

array([1, 2, 3, 4], dtype=int64)

In [64]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [65]:
# Encoding classes to numbers.
# sklearn

In [66]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [67]:
encoder = LabelEncoder()

In [68]:
output = encoder.fit_transform(df['brand'])

In [69]:
output.__class__

numpy.ndarray

In [70]:
output

array([19, 17, 20, ...,  4,  1,  1])

In [71]:
df['brand'] = output

In [72]:
df['brand'].unique()

array([19, 17, 20, 21,  6,  5,  1, 18,  2, 11, 15, 12,  3,  7,  4, 10,  0,
        9, 16, 13, 22, 14,  8])

In [73]:
x = df.drop('price', axis=1)
y = df[['price']]

In [74]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state=42)

In [75]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [76]:
from sklearn.linear_model import LinearRegression

In [77]:
lr = LinearRegression() 

In [78]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [79]:
lr.score(xtrain, ytrain) * 100

65.83186303624649

In [80]:
lr.score(xtest, ytest) * 100

71.75947383086564

In [81]:
pred = lr.predict(xtest)

In [82]:
ytest['pred'] = pred.ravel()
ytest

price           pred
4909   88400.0  150683.502736
1942  102850.0  246408.764116
5763   67000.0   94949.236564
4800   30000.0    2790.775522
7614   20000.0    6456.787056
...        ...            ...
5653  395000.0  411532.041280
609   140000.0  102647.279228
4211   54500.0   37079.005236
6379  114000.0  238205.040245
647    36000.0   36702.672355

[1465 rows x 2 columns]